import numpy as np

class Session:
    def __init__(self, tables: list[str], depth: int, symbols: list[str]) -> None: ...
    def reserve(self, rows: int, /) -> None: ...
    def feed(self, buf: bytes | np.ndarray, /) -> None: ...
    def rows(self) -> int: ...
    def take(self, table: str, /) -> dict[str, np.ndarray]: ...
    def take_symbols(self) -> list[tuple]: ...
    def mpids(self) -> list[str]: ...
    def stats(self) -> dict: ...
