import numpy as np

class Session:
    def __init__(self, tables: list[str], depth: int, symbols: list[str]) -> None: ...
    def reserve(self, rows: int, /) -> None: ...
    def feed(self, buf: bytes | np.ndarray, /) -> None: ...
    def rows(self) -> int: ...
    def take_bbo(self) -> dict[str, np.ndarray]: ...
    def take_trades(self) -> dict[str, np.ndarray]: ...
    def take_messages(self) -> dict[str, np.ndarray]: ...
    def take_depth(self) -> dict[str, np.ndarray]: ...
    def take_events(self) -> dict[str, np.ndarray]: ...
    def take_noii(self) -> dict[str, np.ndarray]: ...
    def take_halts(self) -> dict[str, np.ndarray]: ...
    def take_reg_sho(self) -> dict[str, np.ndarray]: ...
    def take_luld(self) -> dict[str, np.ndarray]: ...
    def take_symbols(self) -> list[tuple]: ...
    def mpids(self) -> list[str]: ...
    def stats(self) -> dict: ...
